# Form implementation generated from reading ui file 'audioDownloader.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
# from main import Ui_MainWindow as mw
# from youtubeWindow import youtubeDownloader as yd


class Ui_audioDownloader(object):
    def setupUi(self, audioDownloader, mw):
        self.ad = audioDownloader
        self.mw = mw
        audioDownloader.setObjectName("audioDownloader")
        audioDownloader.resize(500, 600)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            audioDownloader.sizePolicy().hasHeightForWidth())
        audioDownloader.setSizePolicy(sizePolicy)
        audioDownloader.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(parent=audioDownloader)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 60, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Bauhaus 93")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.spinBox = QtWidgets.QSpinBox(parent=self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(250, 60, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Bauhaus 93")
        font.setPointSize(18)
        self.spinBox.setFont(font)
        self.spinBox.setObjectName("spinBox")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(320, 60, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Bauhaus 93")
        font.setPointSize(18)
        font.setBold(False)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(10, 120, 481, 441))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 479, 439))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 10, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Bauhaus 93")
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.backClicked)
        audioDownloader.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=audioDownloader)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 22))
        self.menubar.setObjectName("menubar")
        audioDownloader.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=audioDownloader)
        self.statusbar.setObjectName("statusbar")
        audioDownloader.setStatusBar(self.statusbar)
        audioDownloader.setWindowIcon(QtGui.QIcon('./assets/logo.png'))

        self.retranslateUi(audioDownloader)
        QtCore.QMetaObject.connectSlotsByName(audioDownloader)

    def retranslateUi(self, audioDownloader):
        _translate = QtCore.QCoreApplication.translate
        audioDownloader.setWindowTitle(_translate(
            "audioDownloader", "Audio Story Downloader"))
        self.label.setText(_translate("audioDownloader", "Numbers of File: "))
        self.pushButton.setText(_translate("audioDownloader", "generate"))
        self.pushButton_2.setText(_translate("audioDownloader", "<- BACK"))

    def backClicked(self):
        self.mw.show()
        self.ad.hide()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    audioDownloader = QtWidgets.QMainWindow()
    ui = Ui_audioDownloader()
    ui.setupUi(audioDownloader,'Dummy')
    audioDownloader.show()
    sys.exit(app.exec())
