AUDIO_STORY_CHANNEL: dict = {
    "বাংলা": {
        "Mirchi Bangla": "https://www.youtube.com/@MirchiBangla/videos",
        "Mir Afsar Ali": "https://www.youtube.com/@realmir/videos",
        "গল্পকথন by কল্লোল": "https://www.youtube.com/@kollol/videos",
        "221B Harrison Road": "https://www.youtube.com/@221BHarrisonRoad2019/videos",
        "Eso Golpo Kori": "https://www.youtube.com/@EsoGolpoKori/videos",
        "Eso Golpo Kori Prime | Bengali Classics Stories": "https://www.youtube.com/@EsoGolpoKoriPrime/videos",
        "Vale of Tales": "https://www.youtube.com/@ValeofTales/videos",
        "THE TRINITY": "https://www.youtube.com/@THETRINITY2020/videos",
        "Kahon": "https://www.youtube.com/@kahonstory/videos",
        "Thriller Station": "https://www.youtube.com/@thrillerstation4876/videos",
        "Golpo kotha": "https://www.youtube.com/@Golpokothaayan/videos",
        "Bong Story Circle": "https://www.youtube.com/@Bongstorycircle/videos",
        "Ferari Mon - A Pure Soul": "https://www.youtube.com/@FerariMonAPureSoul11/videos",
        "Audio Book Bangla by Faheem": "https://www.youtube.com/@AudioBookBanglabyFaheem/videos",
        "JamHub Studio": "https://www.youtube.com/@JamHubStudio/videos",
        "KATHAK KAUSIK": "https://www.youtube.com/@kathakkausik/videos",
        "9F10 Entertainments": "https://www.youtube.com/@9F10/videos",
        "Bangla Story Studio": "https://www.youtube.com/@BanglaStoryStudioO/videos",
        "Bengali Classics By Arnab": "https://www.youtube.com/@BengaliClassicsByArnab/videos",
        "Galpo Salpo / গল্প স্বল্প": "https://www.youtube.com/@galposalpo3317/videos",
        "Golper Jonyo": "https://www.youtube.com/@GolperJonyo/videos",
        "New Suspense Stories": "https://www.youtube.com/@NewSuspenseStories/videos",
        "Radio Milan Audio Story": "https://www.youtube.com/@RadioMilan/videos",
        "The Hypnotic Chroniclers": "https://www.youtube.com/@TheHypnoticChroniclers/videos",
        "Thrill Studio": "https://www.youtube.com/@ThrillStudioo/videos",
        "addabuzz bengali audio story": "https://www.youtube.com/@addabuzzbengaliaudiostory/videos",
        "Midnight Horror Station": "https://www.youtube.com/@mhstation/videos",
        "Golpo Shikari Bengali Audio Story": "https://www.youtube.com/@golpo_shikari/videos",
        "The Story Lines": "https://www.youtube.com/@TheStoryLines/videos",
        "86.7 Tomar FM": "https://www.youtube.com/@867TomarFM/videos",
    },
    "English": {
        "English Audio Books": "https://www.youtube.com/@englishaudiobooks1014/videos",
        "LibriVox Audiobooks": "https://www.youtube.com/@LibriVoxAudiobooks/videos",
        "Steve Parker Audiobooks": "https://www.youtube.com/@SteveParkerAudiobooks/videos",
        "Audio Books": "https://www.youtube.com/@Audio-Books/videos",
        'Steven "Red Fox" Garnett': "https://www.youtube.com/@redfoxvoice/videos",
        "Public Domain Audiobooks": "https://www.youtube.com/@publicdomainaudiobooks21/videos",
        "Greatest AudioBooks": "https://www.youtube.com/@GreatestAudioBooks/videos",
        "Audiobooks: A Collection of Great Books": "https://www.youtube.com/@audiobooksacollectionofgre2012/videos",
    }
}
