SCREEN_WIDTH: int = 0
SCREEN_HEIGHT: int = 0
NUMBER_OF_ELEMENT_FOR_CAROUSEL: int = 3
TOTAL_ELEMENT_FOR_CAROUSEL: int = 10
CAROUSEL_HEIGHT: int = 200
CAROUSEL_WIDTH: int = 400
DOWNLOAD_BOX_HEIGHT = 60
